- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifests
      kubernetes.core.k8s:
        state: present
        src: ./k8s/deployment.yaml
        namespace: test
