name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Install Kubernetes Python module
        run: sudo apt install python3-kubernetes

      - name: Ansible Deploy
        run: ansible-playbook k8s_deploy.yml

