name: Deploy MyApp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: deinlorean/custom-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run tests
        run: pytest

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin | echo "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
