name: Deploy MyApp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: deinlorean/custom-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run tests
        run: pytest
